# Generated by Django 4.0.5 on 2022-06-09 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.BigIntegerField()),
                ('language', models.CharField(choices=[('ENG', 'English'), ('SPA', 'Spanish'), ('CHI', 'Chinese'), ('FRA', 'French'), ('GER', 'German'), ('JPN', 'Japanese'), ('AR', 'Arabic'), ('UR', 'URDU')], max_length=3)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('PKR', 'Pakistani Rupee'), ('EUR', 'Euro'), ('GBP', 'Pound')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='GeoPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon_name', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('poly', models.TextField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='GeoPolygon_Provider', to='api.provider')),
            ],
        ),
    ]
