# Generated by Django 4.0.5 on 2022-06-10 12:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geopolygon',
            name='poly',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='geopolygon',
            name='polygon_name',
            field=models.CharField(default='newpoly', max_length=256),
        ),
        migrations.AlterField(
            model_name='geopolygon',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='geopolygon',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.provider'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('EUR', 'Euro'), ('GBP', 'Pound')], max_length=3),
        ),
        migrations.AlterField(
            model_name='provider',
            name='language',
            field=models.CharField(choices=[('ENG', 'English'), ('SPA', 'Spanish'), ('CHI', 'Chinese'), ('FRA', 'French'), ('GER', 'German'), ('HIN', 'Hindi'), ('JPN', 'Japanese'), ('AR', 'Arabic')], max_length=3),
        ),
    ]
